### ISSUE TITLE
export to XML feature

### ISSUE THREAD

**Issue by onlinebizsoft** [Overdose-Digital/magento2-cms-management#10]
1. You have a nice feature where we can update the content in XML and get them updated to Magento however there is no command to export existing CMS pages/blocks to XML so we can get started from there?

2. Another question, some stores might have many store with many page and blocks so having all in one XML files sounds too big to edit/update? I think we need to split them into multiple files by some segments or simply by format of ID-some-human-name for each page/block?

3. Last thing, right now the XML import feature just overwriting the existing content? Why don't we put a timestamp in the XML file and if the timestamp is older than the timestamp in DB then we should stop importing?

**Comment by orthener** [comment]
Hi, @onlinebizsoft 

1) You need it like exaples? We can put some `exaple.xml` to the module.

2) It makes sense. Need discuss with team.

3) If you are writing a file for import, it means that "you know what to do".
Can you, pls, describe case with steps?

**Comment by onlinebizsoft** [comment]
@orthener 
1.Not really, it is an XML format plus some kind of IDs so you can see it is very hard and take time for people to create it from beginning. 
Beside this, if we have an existing website with a lots of pages and CMS pages already then we will want to start with a snapshot of all pages/blocks then put them on git then start editing content.
3.I know but there are many cases
- What happen when someone from other teams have edited some contents in admin directly without informing to the rest of team?

My idea for using this as a completely alternative solution for editing content so normally we would keep all pages/blocks on GIT and keep update them there for each code version, each deployment and we ALWAYS run update every time we deploy new code version -> it should be safe without overwriting any newer content

If any item with older timestamp wont get imported and users have the list to be checked and they can attempt to export new content and update to git first then edit parts needed again.

**Comment by orthener** [comment]
This module was created not for "keeping all CMS content in git". Module has "history" feature for this. And company/dev should do DB backups periodicaly.
Then you should keep all DB data in git :smile: .
Also much easer use "import/export" feature:
- https://i.imgur.com/uV9bmG4.png
- https://i.imgur.com/szw8wy0.png

Anyway we going to think about:
- export in XML
- import from separate  XML files

**Comment by onlinebizsoft** [comment]
@orthener I understand your point.

But in fact, CMS page/blocks are updated very often together with a deployment (new code and new content is needed) therefore it would be great if they are version-managed with git.

Based on your current module, I found it really matching. The only things was missing
- Export exiting content to your XML format
- Splitting multiple XML files to avoid a very big file

Your current import/export feature can work however the json format is impossible to read and edit therefore it can be used to export content from a dev site then import to a prod site manually and you can see this can create mistake, especially you may have mixed of out of dated and new content on dev site so it is hard to control.
Using the XML way then you automate importing same thing to dev site then prod site without worrying about mistakes :)

**Comment by onlinebizsoft** [comment]
@orthener just wondering if you had some internal discussions with your team?

**Comment by orthener** [comment]
@onlinebizsoft Yes. Ticket in work
Current progress:
```
Changelog:
- separate import/export
- add export to xml
- add export each CMS entity to separate files in one archive
- add import from xml
- fix import from json
Next step:
- change import/export xml structure as example:
Overdose/CMSContent/etc/cms_block_data.xml.sample
Overdose/CMSContent/etc/cms_page_data.xml.sample
```

**Comment by onlinebizsoft** [comment]
@orthener perfect! I can't wait to test it.

**Comment by onlinebizsoft** [comment]
@orthener I see you have almost done with the update, do you have any idea when it could be released?

**Comment by orthener** [comment]
Hi @onlinebizsoft :slightly_smiling_face:
Our dev team busy with another tasks now. Pluning by the end of this year.

**Comment by orthener** [comment]
@onlinebizsoft It seems that after 9 months we gave birth to a release )
