### ISSUE TITLE
License

### ISSUE THREAD

**Issue by twosg** [Overdose-Digital/magento2-cms-management#13]
Hey, this looks very interesting.

Where can I find information about the license?

**Comment by orthener** [comment]
@twosg Hey.
Looks like we miss this point )
Will add with next release. Most likely it will be like Copyleft / FLOSS.

**Comment by orthener** [comment]
We added License file
Check, pls
(Main idea: free to use, but don't sell)
cc: @twosg

**Comment by twosg** [comment]
Thanks @orthener for clarifying!
