### ISSUE TITLE
Return type error on bin/magento od:cms:upgrade -t block

### ISSUE THREAD

**Issue by yevhen-slabonoha** [Overdose-Digital/magento2-cms-management#19]
Hi, 

I would like to inform you that while running CLI command bin/magento od:cms:upgrade -t block, I received an error:

There is an error in /app/vendor/symfony/console/Command/Command.php at line: 301
Return value of "Overdose\CMSContent\Console\Command\CMSUpgradeCommand\Interceptor::execute()" must be of the type int, "null" returned.#0 /app/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

![Selection_023](https://github.com/Overdose-Digital/magento2-cms-management/assets/101104894/4d24fc43-a2aa-49b9-bfc1-1d39a0847e70)

I found that the Command::execute() method needs to get in result int value, and void is not applicable here.
So I guess, as the fast solution on that just return in
**vendor/overdose/module-cmscontent/Console/Command/CMSUpgradeCommand.php:102** 
after  **$output->writeln('<info>Upgrade Completed!</info>');** 
something like: **return 1;**

We are using:
Adobe Commerce 2.4.6
Module version:[v2.0.4](https://github.com/Overdose-Digital/magento2-cms-management/releases/tag/v2.0.4)

Thank you!

**Comment by yevhen-slabonoha** [comment]
Hi, 

I've been found another issue with the import CMS blocks via CLI, after investigating that blocks not creating during import, I found the root cause in the file **vendor/overdose/module-cmscontent/Model/Dir/Reader.php**

The issue happened because variable **$fileIterators** in the parent class **Magento\Framework\Module\Dir\Reader** is private, and private variables are visible only within the class where it is declared.

![image](https://github.com/Overdose-Digital/magento2-cms-management/assets/101104894/afabe1cf-177b-47e4-a244-bc88ace5c259)

So, the fix is to add in the class body:

`/**
     * Found configuration files grouped by configuration types (filename).
     *
     * @var array
     */
    private $fileIterators = [];`

![image](https://github.com/Overdose-Digital/magento2-cms-management/assets/101104894/f1da6b0d-b2eb-42a7-a215-873dda14c827)

Thank you in advance!

**Comment by orthener** [comment]
Sorry for the delay.

Release v2.0.5 contain required fixes - https://github.com/Overdose-Digital/magento2-cms-management/releases/tag/v2.0.5
